export const PROMO_ACTIVE = true;

export const PLANS = [
  {
    name: "Free",
    price: 0,
    promoPrice: 0,
    description: "Perfect to try out Burnzy with limited monthly access.",
    features: [
      "2 Topic Analyses / month",
      "2 Channel Analyses / month",
      "2 Niche Analyses / month",
      "1 Channel Insights report / month",
      "2 Trend Idea generations / month",
      "1 Extra Trend Ideas refills / month",
      "1 Explore Idea / month",
      "0 Content Plans / month",
      "1 Idea Breakdown / month",
      "2 Thumbnail generations / month",
      "2 Thumbnail edits / month",
      "1 Face swap / month",
      "Basic community support",
    ],
    buttonText: "Start for Free",
    highlight: false,
  },
  {
    name: "Pro",
    price: 21.99,
    promoPrice: 19.99,
    description: "For creators & marketers producing content consistently.",
    features: [
      "20 Topic Analyses / month",
      "20 Channel Analyses / month",
      "20 Niche Analyses / month",
      "20 Channel Insights reports / month",
      "12 Trend Idea generations / month",
      "20 Extra Trend Ideas refills / month",
      "15 Explore Ideas / month",
      "6 Content Plans / month",
      "25 Idea Breakdowns / month",
      "80 Thumbnail generations / month",
      "30 Thumbnail edits / month",
      "12 Face swaps / month",
      "Access to all features",
      "Email support",
    ],
    buttonText: "Upgrade to Pro",
    highlight: true,
  },

  {
    name: "Ultra",
    price: 59.99,
    promoPrice: 49.99,
    description: "Maximum self-serve capacity for power users scaling output.",
    features: [
      "60 Topic Analyses / month",
      "60 Channel Analyses / month",
      "60 Niche Analyses / month",
      "60 Channel Insights reports / month",
      "50 Trend Idea generations / month",
      "40 Extra Trend Ideas refills / month",
      "50 Explore Ideas / month",
      "20 Content Plans / month",
      "60 Idea Breakdowns / month",
      "200 Thumbnail generations / month",
      "80 Thumbnail edits / month",
      "25 Face swaps / month",
      "Highest processing priority",
      "Priority support",
    ],
    buttonText: "Upgrade to Ultra",
    highlight: false,
  },
];
